from .userController import UserController
from .postagemController import PostagemController
from .comentarioController import ComentarioController
from .denunciaController import DenunciaController
from .seguidorController import SeguidorController